### PR TITLE
Add 5 new levels to draft (by Wuzzy)

### PR DESCRIPTION
**Pull request by Wuzzy2**
Yay! I created 5 new levels of mixed difficulty which I want to contribute:

* In the Attic
* Magic Steel
* Construction Yard
* Butterflies of Doom
* Balloon Blues

All levels have been tested (by me, however) and should already be playable.
I have put them into the `draft` folder for now.

### CODE REVIEW

**Comment by kaa-ching** [comment]
I like the levels a lot. They are closer to TIM levels than what I designed so far.
So far, I only solved *Magic Steel* and *In the Attic* - but I'm at work, so I shouldn't spend time on it.

Note that two of your levels have the locale issue as mentioned in #66. I will fix that after the merge.

None of your levels have hints, so they cannot be added to the regression tests. 
I should fix that, too :wink: 
(too early to make it mandatory for new levels)

**Comment by kaa-ching** [comment]
Would you mind if I write a blog post about your levels?

**Comment by Wuzzy2** [comment]
No, I won't mind.
By the way, Magic Steel has a small hint.

And whoops. I coulld swear I have fixed the commas. :-(

**Comment by kaa-ching** [comment]
changeset 23c85b7 fixes the locale issues.

**Comment by kaa-ching** [comment]
Is this meant to be the solution to Balloon Blues?
Somehow it feels wrong... Used only have the stuff available...

balloon-blues

**Comment by Wuzzy2** [comment]
Well, let's say it isn't the only solution. I have noticed that this solution is possible as well but I did not bother to change the thing.

**Comment by amarsman** [comment]
Personally I don't mind different ways to Rome, if for those solutions the difficulty is similar. If a level is meant to be difficult there should not be a simple solution also. In that case I consider it a bug.

**Comment by Wuzzy2** [comment]
Okay, I have made some changes to the level in PR #89.

**Pull request merged**
