### PR TITLE
Add new level: The Pit

### PR DESCRIPTION
**Pull request by Wuzzy2**
I want to contribute yet another level: The Pit. It's a really complex and big level and it took a lot of time to tweak it so it works fine (if you know how). I think it is also difficult or very difficult (at least I hope so).
Have fun!

Some notes:
* It contains the ToyChest object, but with mass set to 0. :P
* I intend the detonator boxes to have fixed (unchangable) phone numbers but I don't know how to do that. But I don't if it matters much for this level; I don't know if the level becomes much easier/harder if the player is allowed to swap the phone numbers or they aren't pre-set at all

### CODE REVIEW

**Comment by kaa-ching** [comment]
So far, after trying for an hour, I have two solutions to get 2 out of five tennisballs in the chest.
I have no clue how to get the bottom two balls to move. 
I believe the dominos to be a decoy - I don't see how I could ever trigger them. And they would be useful to start the right bowlingball.
So, you might want to add slightly more hints to the level. Also, I suggest to fill up spaces where you nothing can roll, e.g. at the top-right.

**Comment by Wuzzy2** [comment]
I won't add hints, because this will reduce the difficulty of the level. :P The average difficulty of TBE levels is still very low, I am trying my best to increase it. ;-)

I don't know what you mean by “fill up spaces” and why you suggest this. Is this important?

**Comment by kaa-ching** [comment]
These are the holes I'm talking about. I'm pretty sure that one or two have to do with the solution I haven't found yet. But you might want to plug the rest. the-pit-holes

**Comment by Wuzzy2** [comment]
Okay, I agree, some of the holes were really ugly. The visuals could be improved, so I did it here:

https://github.com/kaa-ching/tbe/pull/134

**Comment by kaa-ching** [comment]
yay. I doesn't help me at all - I still don't have a clue how to complete the level :wink:

**Pull request merged**
